export const GET_SINGLE_RECIPE = "GET_SINGLE_RECIPE";
export const GET_RECIPE_FAIL = "GET_RECIPE_FAIL";
export const EDIT_SINGLE_RECIPE = "EDIT_SINGLE_RECIPE";
export const EDIT_SINGLE_RECIPE_FAIL = "EDIT_SINGLE_RECIPE_FAIL";
export const DELETE_SINGLE_RECIPE = "DELETE_SINGLE_RECIPE";
export const DELETE_SINGLE_RECIPE_FAIL = "DELETE_SINGLE_RECIPE_FAIL";



