export const ADD_MY_RECIPE = "ADD_MY_RECIPE";
export const ADD_MY_RECIPE_FAIL = "ADD_MY_RECIPE_FAIL";
export const EDIT_MY_RECIPE = "EDIT_MY_RECIPE";
export const DELETE_MY_RECIPE = "DELETE_MY_RECIPE";
export const GET_ALL_USER_RECIPES = "GET_ALL_USER_RECIPES";
export const GET_RECIPES_FAIL = "GET_RECIPES_FAIL";
